### ISSUE TITLE
トーストの作成

### ISSUE THREAD

**Issue by momeemt** [sohosai/qr-frontend#12]
Figmaの「物品登録（成功）」「物品登録（失敗）」フレームの下部に表示されている、緑/赤のUIコンポーネントを「トースト」と呼びます。
Toastコンポーネントを、`src/components/toast.tsx`に作成してください。

### Props
`kind`: `successful`か`failed`を取って、前者の場合はbg-colorを緑に、後者の場合は赤にしてください。
`text`: 表示するテキストを`string`値で取ってください

**Comment by puripuri2100** [comment]
やる
