### ISSUE TITLE
`yarn dev`と`yarn start`で表示が違うバグ

### ISSUE THREAD

**Issue by Myxogastria0808** [sohosai/qr-frontend#124]
- [x] 各アイコンが4つ格子状に並ばないで縦一列になっている
- [x] アイコンの大きさが意図よりも小さい

---

- [x] Headerコンポーネントがレスポンシブになっていない

**Comment by puripuri2100** [comment]
```
<Box sx={{ display: 'flex' }} className='header-PC'>
</Box>
```
で`display`要素が衝突を起こしているのが原因なので
```
<div className='header-PC'>
  <Box sx={{ display: 'flex' }}>
  </Box>
</div>
```
として修正する

**Comment by Myxogastria0808** [comment]
原因究明と修正の程、ありがとうございます。
[fixbug/#124-fix-style-bug](https://github.com/sohosai/qr-frontend/tree/fixbug/%23124-fix-style-bug)
このブランチにその他の問題点 (Topコンポーネントに2か所ほどまだ解決していない問題があります。)の修正結果を反映させておきます。

**Comment by puripuri2100** [comment]
これはHeaderのやつか
Topのやつも同様に衝突が起きて相

**Comment by Myxogastria0808** [comment]
Headerの問題でした。
すいません、勘違いしてました。
Topの方は、こちらで直しておきます。

**Comment by puripuri2100** [comment]
自分の勘違いが原因です
申し訳ない

**Comment by puripuri2100** [comment]
とりあえず[fixbug/#124-fix-style-bug](https://github.com/sohosai/qr-frontend/tree/fixbug/%23124-fix-style-bug)でプルリクエストを立ててもらえると良さそう

**Comment by Myxogastria0808** [comment]
@puripuri2100 さんがしてくださったHeaderコンポーネントの変更分は、どのブランチにpushされましたか？

**Comment by puripuri2100** [comment]
まだpushしてないです
ブランチのmergeとか色々やるのはだるいと思うので、[fixbug/#124-fix-style-bug](https://github.com/sohosai/qr-frontend/tree/fixbug/%23124-fix-style-bug)ブランチに @Myxogastria0808 さんがコミットしてしまって良いと思います

**Comment by Myxogastria0808** [comment]
了解です。

**Comment by puripuri2100** [comment]
@Myxogastria0808 このIssueの一番上に「認識している、意図とは違う表示になっている箇所」をチェックボックス形式で書き、解決したところについてはチェックを入れておいてください
一部自分がわかる部分は書いておきました
これにより今解決しないといけない課題がわかるので便利です

**Comment by Myxogastria0808** [comment]
了解です。
