### ISSUE TITLE
実装する機能一覧

### ISSUE THREAD

**Issue by toririm** [sohosai/qr-frontend#37]
- 物品の登録ページを作る --- 優先順3
  - 物品名[入力]
  - 説明[入力]
  - 格納場所（部屋）[プルダウン]
  - 親物品[検索機能付きプルダウン]
  - ~~QR印刷サイズ[プルダウン]~~ 今は実装しない
  - 登録ボタン
  - 登録成功/失敗 表示
- ~~QRの印刷ページを作る~~ 今は実装しない
  - 印刷待ちの物品を取得し列挙
  - 印刷ボタン
  - PDFを表示
- 物品の個別情報閲覧ページを作る --- 優先順2
  - DBに入っている各種情報を取得し表示
- 物品の使用/返却ページを作る --- 優先順1
  - QR読み取りボタン
  - QR読み取り -> 対象の物品を状態を登録
    - 使用
      - 使用場所
      - 使用者
      - 使用登録ボタン
    - 返却
      - 返却済ボタン
- ~~ログインページ~~ 今は実装しない

**Comment by toririm** [comment]
PRのマージ方針
- momeemtの #30 と #21 以外は未完成なのでマージしない
- 上2つも8/26までにConflictが解消されなければマージしない

**Comment by puripuri2100** [comment]
QRの印刷ページは今必須ですか？
必須ではないように思えるのですが

物品の個別のページが要件に無いような気がしますが、必要ですよね？

**Comment by toririm** [comment]
QR印刷ページは現状で必須ではないです

ご指摘の通り、むしろ物品の個別ページの方が優先度が高いです…

**Comment by toririm** [comment]
物品データは既に収集されていて、そしてプレ雙で使用することを考えると、直近で必要な機能では「物品を使用する/返却」と「物品個別情報閲覧」の2点の優先度が高そうです。

既に登録ページに着手している中、申し訳ないのですが、再度整理してみましたので、ご確認ください。

**Comment by puripuri2100** [comment]
✅ 登録ページはできた #41

**Comment by puripuri2100** [comment]
✅個別ページはできた #41

**Comment by puripuri2100** [comment]
✅ 使用ページができた #44

**Comment by puripuri2100** [comment]
✅ 返却ページができた #48

**Comment by puripuri2100** [comment]
全部実装したのでclose
