### ISSUE TITLE
物品登録ページに要素を追加する

### ISSUE THREAD

**Issue by puripuri2100** [sohosai/qr-frontend#38]
#37 の要件に則れば他に

- 親物品（検索機能付き）
- 登録成功失敗表示

が必要らしい
API呼び出しが必要なのでqr-backendと連携させる

**Comment by toririm** [comment]
検索機能はOptionalで大丈夫です！
辛かったら全列挙プルダウンで…

**Comment by puripuri2100** [comment]
#56 で修正
