### ISSUE TITLE
ヘッダーを作る

### ISSUE THREAD

**Issue by momeemt** [sohosai/qr-frontend#7]
<img width="646" alt="スクリーンショット 2023-02-07 11 04 40" src="https://user-images.githubusercontent.com/43488453/217129193-315ec684-7cb4-46e2-88fd-552bd7cffc14.png">

# 実装方針
- Headerコンポーネントを作成する
- ハンバーガーメニューはまだハリボテで大丈夫です
- Figmaで設定されている色を参照して実装するようにしてください！

**Comment by puripuri2100** [comment]
回収します

**Comment by puripuri2100** [comment]
ハンバーガーメニューも実装する
