### ISSUE TITLE
APIを叩くコードをuseEffect外に出す

### ISSUE THREAD

**Issue by puripuri2100** [sohosai/qr-frontend#72]
useEffect内でやるのはよくないらしい

- [swr](https://swr.vercel.app/ja)
- [tanstack query](https://tanstack.com/query/latest)

などを使うと解決するらしい？

**Comment by puripuri2100** [comment]
自分では無理そうな気がしてきた
`yarn build`をすると`https://qr.sohosai.com/items/[fixtures_id]`というURLについて`fixture_id`が定まらないために`useSWR`が無限に回りまくって終了する

**Comment by puripuri2100** [comment]
ふむ
https://github.com/vercel/swr/blob/main/examples/server-render/pages/%5Bpokemon%5D.js

**Comment by iorin-io** [comment]
見るだけ見てみます
